/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as PengujiIndexRouteImport } from './routes/penguji/index'
import { Route as PengujiLoginRouteImport } from './routes/penguji/login'
import { Route as ScannerIndexRouteImport } from './routes/scanner/index'
import { Route as ScannerLoginRouteImport } from './routes/scanner/login'
import { Route as SiswaIndexRouteImport } from './routes/siswa/index'
import { Route as SiswaLoginRouteImport } from './routes/siswa/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PengujiIndexRoute = PengujiIndexRouteImport.update({
  id: '/penguji/',
  path: '/penguji/',
  getParentRoute: () => rootRouteImport,
} as any)
const PengujiLoginRoute = PengujiLoginRouteImport.update({
  id: '/penguji/login',
  path: '/penguji/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerIndexRoute = ScannerIndexRouteImport.update({
  id: '/scanner/',
  path: '/scanner/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerLoginRoute = ScannerLoginRouteImport.update({
  id: '/scanner/login',
  path: '/scanner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaIndexRoute = SiswaIndexRouteImport.update({
  id: '/siswa/',
  path: '/siswa/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaLoginRoute = SiswaLoginRouteImport.update({
  id: '/siswa/login',
  path: '/siswa/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/penguji/login': typeof PengujiLoginRoute
  '/scanner/login': typeof ScannerLoginRoute
  '/siswa/login': typeof SiswaLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/penguji/': typeof PengujiIndexRoute
  '/scanner/': typeof ScannerIndexRoute
  '/siswa/': typeof SiswaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/penguji/login': typeof PengujiLoginRoute
  '/scanner/login': typeof ScannerLoginRoute
  '/siswa/login': typeof SiswaLoginRoute
  '/admin': typeof AdminIndexRoute
  '/penguji': typeof PengujiIndexRoute
  '/scanner': typeof ScannerIndexRoute
  '/siswa': typeof SiswaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/penguji/login': typeof PengujiLoginRoute
  '/scanner/login': typeof ScannerLoginRoute
  '/siswa/login': typeof SiswaLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/penguji/': typeof PengujiIndexRoute
  '/scanner/': typeof ScannerIndexRoute
  '/siswa/': typeof SiswaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/penguji/login'
    | '/scanner/login'
    | '/siswa/login'
    | '/admin/'
    | '/penguji/'
    | '/scanner/'
    | '/siswa/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/penguji/login'
    | '/scanner/login'
    | '/siswa/login'
    | '/admin'
    | '/penguji'
    | '/scanner'
    | '/siswa'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin/login'
    | '/penguji/login'
    | '/scanner/login'
    | '/siswa/login'
    | '/admin/'
    | '/penguji/'
    | '/scanner/'
    | '/siswa/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  PengujiLoginRoute: typeof PengujiLoginRoute
  ScannerLoginRoute: typeof ScannerLoginRoute
  SiswaLoginRoute: typeof SiswaLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PengujiIndexRoute: typeof PengujiIndexRoute
  ScannerIndexRoute: typeof ScannerIndexRoute
  SiswaIndexRoute: typeof SiswaIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penguji/': {
      id: '/penguji/'
      path: '/penguji'
      fullPath: '/penguji/'
      preLoaderRoute: typeof PengujiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penguji/login': {
      id: '/penguji/login'
      path: '/penguji/login'
      fullPath: '/penguji/login'
      preLoaderRoute: typeof PengujiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner/': {
      id: '/scanner/'
      path: '/scanner'
      fullPath: '/scanner/'
      preLoaderRoute: typeof ScannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner/login': {
      id: '/scanner/login'
      path: '/scanner/login'
      fullPath: '/scanner/login'
      preLoaderRoute: typeof ScannerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/': {
      id: '/siswa/'
      path: '/siswa'
      fullPath: '/siswa/'
      preLoaderRoute: typeof SiswaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/login': {
      id: '/siswa/login'
      path: '/siswa/login'
      fullPath: '/siswa/login'
      preLoaderRoute: typeof SiswaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  PengujiLoginRoute: PengujiLoginRoute,
  ScannerLoginRoute: ScannerLoginRoute,
  SiswaLoginRoute: SiswaLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  PengujiIndexRoute: PengujiIndexRoute,
  ScannerIndexRoute: ScannerIndexRoute,
  SiswaIndexRoute: SiswaIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
