/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as BaristaIndexRouteImport } from './routes/barista/index'
import { Route as BaristaLoginRouteImport } from './routes/barista/login'
import { Route as PengawasWrIndexRouteImport } from './routes/pengawas-wr/index'
import { Route as PengujiIndexRouteImport } from './routes/penguji/index'
import { Route as PengujiLoginRouteImport } from './routes/penguji/login'
import { Route as ScannerIndexRouteImport } from './routes/scanner/index'
import { Route as ScannerLoginRouteImport } from './routes/scanner/login'
import { Route as SiswaIndexRouteImport } from './routes/siswa/index'
import { Route as SiswaLoginRouteImport } from './routes/siswa/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PengujiNilaiSiswaIdRouteImport } from './routes/penguji/nilai.$siswaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BaristaIndexRoute = BaristaIndexRouteImport.update({
  id: '/barista/',
  path: '/barista/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaristaLoginRoute = BaristaLoginRouteImport.update({
  id: '/barista/login',
  path: '/barista/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PengawasWrIndexRoute = PengawasWrIndexRouteImport.update({
  id: '/pengawas-wr/',
  path: '/pengawas-wr/',
  getParentRoute: () => rootRouteImport,
} as any)
const PengujiIndexRoute = PengujiIndexRouteImport.update({
  id: '/penguji/',
  path: '/penguji/',
  getParentRoute: () => rootRouteImport,
} as any)
const PengujiLoginRoute = PengujiLoginRouteImport.update({
  id: '/penguji/login',
  path: '/penguji/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerIndexRoute = ScannerIndexRouteImport.update({
  id: '/scanner/',
  path: '/scanner/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerLoginRoute = ScannerLoginRouteImport.update({
  id: '/scanner/login',
  path: '/scanner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaIndexRoute = SiswaIndexRouteImport.update({
  id: '/siswa/',
  path: '/siswa/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaLoginRoute = SiswaLoginRouteImport.update({
  id: '/siswa/login',
  path: '/siswa/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PengujiNilaiSiswaIdRoute = PengujiNilaiSiswaIdRouteImport.update({
  id: '/penguji/nilai/$siswaId',
  path: '/penguji/nilai/$siswaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/barista/login': typeof BaristaLoginRoute
  '/penguji/login': typeof PengujiLoginRoute
  '/scanner/login': typeof ScannerLoginRoute
  '/siswa/login': typeof SiswaLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/barista/': typeof BaristaIndexRoute
  '/pengawas-wr/': typeof PengawasWrIndexRoute
  '/penguji/': typeof PengujiIndexRoute
  '/scanner/': typeof ScannerIndexRoute
  '/siswa/': typeof SiswaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/penguji/nilai/$siswaId': typeof PengujiNilaiSiswaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/barista/login': typeof BaristaLoginRoute
  '/penguji/login': typeof PengujiLoginRoute
  '/scanner/login': typeof ScannerLoginRoute
  '/siswa/login': typeof SiswaLoginRoute
  '/admin': typeof AdminIndexRoute
  '/barista': typeof BaristaIndexRoute
  '/pengawas-wr': typeof PengawasWrIndexRoute
  '/penguji': typeof PengujiIndexRoute
  '/scanner': typeof ScannerIndexRoute
  '/siswa': typeof SiswaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/penguji/nilai/$siswaId': typeof PengujiNilaiSiswaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/barista/login': typeof BaristaLoginRoute
  '/penguji/login': typeof PengujiLoginRoute
  '/scanner/login': typeof ScannerLoginRoute
  '/siswa/login': typeof SiswaLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/barista/': typeof BaristaIndexRoute
  '/pengawas-wr/': typeof PengawasWrIndexRoute
  '/penguji/': typeof PengujiIndexRoute
  '/scanner/': typeof ScannerIndexRoute
  '/siswa/': typeof SiswaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/penguji/nilai/$siswaId': typeof PengujiNilaiSiswaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/barista/login'
    | '/penguji/login'
    | '/scanner/login'
    | '/siswa/login'
    | '/admin/'
    | '/barista/'
    | '/pengawas-wr/'
    | '/penguji/'
    | '/scanner/'
    | '/siswa/'
    | '/api/auth/$'
    | '/penguji/nilai/$siswaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/barista/login'
    | '/penguji/login'
    | '/scanner/login'
    | '/siswa/login'
    | '/admin'
    | '/barista'
    | '/pengawas-wr'
    | '/penguji'
    | '/scanner'
    | '/siswa'
    | '/api/auth/$'
    | '/penguji/nilai/$siswaId'
  id:
    | '__root__'
    | '/'
    | '/admin/login'
    | '/barista/login'
    | '/penguji/login'
    | '/scanner/login'
    | '/siswa/login'
    | '/admin/'
    | '/barista/'
    | '/pengawas-wr/'
    | '/penguji/'
    | '/scanner/'
    | '/siswa/'
    | '/api/auth/$'
    | '/penguji/nilai/$siswaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BaristaLoginRoute: typeof BaristaLoginRoute
  PengujiLoginRoute: typeof PengujiLoginRoute
  ScannerLoginRoute: typeof ScannerLoginRoute
  SiswaLoginRoute: typeof SiswaLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BaristaIndexRoute: typeof BaristaIndexRoute
  PengawasWrIndexRoute: typeof PengawasWrIndexRoute
  PengujiIndexRoute: typeof PengujiIndexRoute
  ScannerIndexRoute: typeof ScannerIndexRoute
  SiswaIndexRoute: typeof SiswaIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PengujiNilaiSiswaIdRoute: typeof PengujiNilaiSiswaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barista/': {
      id: '/barista/'
      path: '/barista'
      fullPath: '/barista/'
      preLoaderRoute: typeof BaristaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barista/login': {
      id: '/barista/login'
      path: '/barista/login'
      fullPath: '/barista/login'
      preLoaderRoute: typeof BaristaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengawas-wr/': {
      id: '/pengawas-wr/'
      path: '/pengawas-wr'
      fullPath: '/pengawas-wr/'
      preLoaderRoute: typeof PengawasWrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penguji/': {
      id: '/penguji/'
      path: '/penguji'
      fullPath: '/penguji/'
      preLoaderRoute: typeof PengujiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penguji/login': {
      id: '/penguji/login'
      path: '/penguji/login'
      fullPath: '/penguji/login'
      preLoaderRoute: typeof PengujiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner/': {
      id: '/scanner/'
      path: '/scanner'
      fullPath: '/scanner/'
      preLoaderRoute: typeof ScannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner/login': {
      id: '/scanner/login'
      path: '/scanner/login'
      fullPath: '/scanner/login'
      preLoaderRoute: typeof ScannerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/': {
      id: '/siswa/'
      path: '/siswa'
      fullPath: '/siswa/'
      preLoaderRoute: typeof SiswaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/login': {
      id: '/siswa/login'
      path: '/siswa/login'
      fullPath: '/siswa/login'
      preLoaderRoute: typeof SiswaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penguji/nilai/$siswaId': {
      id: '/penguji/nilai/$siswaId'
      path: '/penguji/nilai/$siswaId'
      fullPath: '/penguji/nilai/$siswaId'
      preLoaderRoute: typeof PengujiNilaiSiswaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  BaristaLoginRoute: BaristaLoginRoute,
  PengujiLoginRoute: PengujiLoginRoute,
  ScannerLoginRoute: ScannerLoginRoute,
  SiswaLoginRoute: SiswaLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  BaristaIndexRoute: BaristaIndexRoute,
  PengawasWrIndexRoute: PengawasWrIndexRoute,
  PengujiIndexRoute: PengujiIndexRoute,
  ScannerIndexRoute: ScannerIndexRoute,
  SiswaIndexRoute: SiswaIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PengujiNilaiSiswaIdRoute: PengujiNilaiSiswaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
